### PR TITLE
Minor updates to directory names and naming standards

### PR DESCRIPTION
**Pull request by mrtommyb**
This is a very minor update. Following comments from some project science office folks, we have updated some directory names. 

Updates include:
- update to the launch site
- changed spectroscopy elements folder to PrismGrismSummary
- changed spectroscopy filters folder to FiltersSummary
- used 3 letter month format in dates

### CODE REVIEW

**Comment by sepito** [comment]
Hi Tom, the launch site on our IPAC Roman website is already "Cape Canaveral". So looks like it hasn't changed or did it change in the interim? Do I need to approve this pull request? Thanks, Seppo

**Comment by mrtommyb** [comment]
I changed the launch site from
Cape Canaveral-> Kennedy Space Center, Florida, USA.

**Comment by mrtommyb** [comment]
> Do I need to approve this pull request? Thanks, Seppo

I believe that an STScI person needs to approve the PR. I've assigned this to them.

**Review by rachael-beaton — COMMENTED** [review]
Looks good -- thanks for the tedious work searching out the dates!

**Review by rachael-beaton — APPROVED** [review]

**Comment by rachael-beaton** [comment]
Should be approved -- reach out or submit another request if anything fell through the cracks. :-)

**Comment by sepito** [comment]
OK, I see it now. I guess there was a time delay before the changed information became visible. I will change the parameter file at SSC for our Roman website accordingly. Still waiting for Patrick's permission to proceed with the parameter changes on our website.

**Pull request merged**
