### PR TITLE
Add in Coronagraph parameters.

### PR DESCRIPTION
**Pull request by rzellem**
These params came from the IPAC Roman Parameters website, which I updated with @sepito a few months ago.

### CODE REVIEW

**Comment by mrtommyb** [comment]
It looks like @rzellem created a branch on the spacetelescope/roman-technical-information repository for this rather forking this repository into rzellem/roman-technical-information. 

@tddesjardins should we proceed with this PR as is, or should we delete the coronagraph_parameters branch on the spacetelescope repository, and redo this PR from a fork from @rzellem's personal account?

**Comment by mrtommyb** [comment]
I don't see any issues here @rzellem on first look - I was wondering if there are any additional data products we should include here. Like do we want filter bandpass curves, effective areas, contrast curves, etc. ?

**Comment by rzellem** [comment]
> I don't see any issues here @rzellem on first look - I was wondering if there are any additional data products we should include here. Like do we want filter bandpass curves, effective areas, contrast curves, etc. ?

yep, lemme see what I can find- I think there's some ancillary info that's publicly cleared on the IPAC website, for example

**Comment by tddesjardins** [comment]
> It looks like @rzellem created a branch on the spacetelescope/roman-technical-information repository for this rather forking this repository into rzellem/roman-technical-information.
> 
> @tddesjardins should we proceed with this PR as is, or should we delete the coronagraph_parameters branch on the spacetelescope repository, and redo this PR from a fork from @rzellem's personal account?

@mrtommyb @rzellem I think it's fine if we merge this PR (after the review is complete) and then delete the branch rather than redo-ing. I don't want to make it overly complicated.

**Comment by rzellem** [comment]
> > It looks like @rzellem created a branch on the spacetelescope/roman-technical-information repository for this rather forking this repository into rzellem/roman-technical-information.
> > @tddesjardins should we proceed with this PR as is, or should we delete the coronagraph_parameters branch on the spacetelescope repository, and redo this PR from a fork from @rzellem's personal account?
> 
> @mrtommyb @rzellem I think it's fine if we merge this PR (after the review is complete) and then delete the branch rather than redo-ing. I don't want to make it overly complicated.

is it ok if we adopt that workflow instead (making a new branch on this repo and doing a PR from there)? or do you want us to still fork? a potential reason to make new branches on here instead of PRs from a remote forked repo might be easier tracking/versioning

**Review by sepito — COMMENTED** [review]
The parameter values match those on the IPAC Roman website at https://roman.ipac.caltech.edu/sims/Param_db.html. The only recommendation is to add some description for the neutral density filters (IPAC website has for example "Attenuation factor of Neutral Density filter used for target acquisition (ND 2.25) mounted in FPAM" etc.

**Comment by rzellem** [comment]
ok, thanks, all- I'll adopt the new workflow for future PRs - my apologies for missing that

and I'll also look into posting ancillary info/measurements for CGI - that might take some time to get cleared on the JPL side, so it would be great if we could have this PR approved and merged - who is the correct person to do that?

**Comment by tddesjardins** [comment]
@rzellem that would be me. :) I'm about to do my review. If @sepito and @mrtommyb could approve or approve with comments, then I'll finish mine and merge it today.

**Review by mrtommyb — APPROVED** [review]

**Comment by tddesjardins** [comment]
Thanks, Tom! Rob is double checking with the EXCAM leads that the read noise value is right (it jumped out at me as being very high), but everything else looks good to me. Once we've got that double check, we can either adjust it or merge.

**Comment by rzellem** [comment]
Nathan Bush actually notes that it is more accurately 160 e-

@sepito - can you please also update the IPAC Roman Parameter website for this? I'll update this PR and resubmit in a moment

**Comment by rzellem** [comment]
@tddesjardins - ok, we should be good to merge

sorry for the snafu on PR and branches...I'll start developing locally on my own forked repo and push from there

**Comment by tddesjardins** [comment]
No problem and thank you for following up!!

**Review by tddesjardins — APPROVED** [review]

**Comment by sepito** [comment]
> Nathan Bush actually notes that it is more accurately 160 e-
> 
> @sepito - can you please also update the IPAC Roman Parameter website for this? I'll update this PR and resubmit in a moment

Is this the CGI_Detector_Readnoise parameter that we currently have as 120 e-? I can make the change and put it in the queue together with the WFI parameter changes for which I submitted several GitHub issues for you and Tom to look at. Thanks.

**Comment by rzellem** [comment]
@sepito - yes - I already updated it here on the Github, but it also needs to be updated on the IPAC website, thanks!

**Pull request merged**
