### PR TITLE
Added README files for Coronagraph.

### PR DESCRIPTION
**Pull request by rzellem**
To address issue #30

### CODE REVIEW

**Comment by mrtommyb** [comment]
@rzellem I don't understand this PR. We have already fixed these files in #29

**Comment by mrtommyb** [comment]
Per #30 where we are missing a readme is in data/CoronagraphInstrument/. And this PR does address that. But the other files are already fixed

**Comment by rzellem** [comment]
> @rzellem I don't understand this PR. We have already fixed these files in #29

right- it was to address the lack of a README file in the main CoronagraphInstrument directory - I probably didn't do the forking of the GitHub properly....

**Comment by rzellem** [comment]
The conflicts might be showing because I forked before your PR was merged, @mrtommyb . Let me re-fork and try again.

**Pull request closed without merging**
