### PR TITLE
removing the last updated columns from readme's per #27

### PR DESCRIPTION
**Pull request by mrtommyb**
We decided to remove all the last updated columns from the readme files. This PR implements that change per #27

### CODE REVIEW

**Comment by mrtommyb** [comment]
Does anyone want to review this @tddesjardins @rzellem ?

**Comment by rzellem** [comment]
> Does anyone want to review this @tddesjardins @rzellem ?

@tddesjardins - am I allowed to review this and approve it, or do we need someone from STScI to do that (e.g., you)?

**Comment by tddesjardins** [comment]
I can review right now. I think we ideally wanted one from each partner to review PRs, but in the end I cannot recall if the settings mean someone from SOC has to actually push the button (I think so?).

**Review by tddesjardins — APPROVED** [review]

**Comment by tddesjardins** [comment]
Fixes #27

**Pull request merged**
